# Numpy assignment
- Different tasks will be detailed by comments or text.
- For further reference and resources, it's advised to check out the NumPy documentation.

In [4]:
# Import NumPy as its abbreviation 'np'
import numpy as np

In [5]:
# Create a 1-dimensional NumPy array using np.array()
a1 = np.array([1,2,3])
a1

# Create a 2-dimensional NumPy array using np.array()
a2 = np.array([[1, 2.0, 3.3],
               [4, 5, 6.5]])
a2

array([[1. , 2. , 3.3],
       [4. , 5. , 6.5]])

In [7]:
# Attributes of 1-dimensional array (shape, number of dimensions, data type, size and type)
a1= np.array([1,2,3])
a1.shape, a1.ndim, a1.dtype, a1.size, type(a1)

((3,), 1, dtype('int32'), 3, numpy.ndarray)

In [8]:
# Attributes of 2-dimensional array
a2 = np.array([[1, 2.0, 3.3],
               [4, 5, 6.5]])
a2.shape, a2.ndim, a2.dtype, a2.size, type(a2)

((2, 3), 2, dtype('float64'), 6, numpy.ndarray)

In [9]:
# Create an array of shape (5, 5) with only ones
a=np.ones([5,5])
a

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [14]:
# Create array of shape (3, 3, 5) with only zeros
a=np.zeros((3,3,5))
a

array([[[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]],

       [[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]],

       [[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]]])

In [15]:
# Create a random array with numbers between 0 and 10 of size (7, 2)
np.random.randint(10, size=(7, 2))

array([[0, 3],
       [6, 1],
       [4, 8],
       [7, 7],
       [5, 7],
       [6, 6],
       [6, 8]])

In [19]:
# Create a random array of floats between 0 & 1 of shape (3, 5)
from numpy import random

x = random.rand(3,5)

x

array([[0.62614356, 0.44322187, 0.02663322, 0.9407868 , 0.89640482],
       [0.66308305, 0.46912441, 0.25659167, 0.80419021, 0.66155666],
       [0.95020749, 0.12510666, 0.72799251, 0.86534959, 0.06789522]])

In [22]:
# Create an array of normally distributed random numbers
np.random.randn(5, 3)

array([[-2.43910582,  0.60344123, -0.25104397],
       [-0.16386712, -1.47632969,  1.48698096],
       [-0.02445518,  0.35555132,  0.41701111],
       [ 0.83246186, -0.29339915, -0.02983857],
       [ 0.09512578,  0.66465434, -0.1402185 ]])

In [21]:
# Set the random seed to 42

np.random.seed(42)

# Create a random array of numbers between 0 & 10 of size (4, 6)

random_array = np.random.randint(10, size=(4,6))
random_array

array([[6, 3, 7, 4, 6, 9],
       [2, 6, 7, 4, 3, 7],
       [7, 2, 5, 4, 1, 7],
       [5, 1, 4, 0, 9, 5]])

In [23]:
# Copy the code from the cell above and run it again

# Set the random seed to 42

np.random.seed(42)

# Create a random array of numbers between 0 & 10 of size (4, 6)

random_array = np.random.randint(10, size=(4,6))
random_array

array([[6, 3, 7, 4, 6, 9],
       [2, 6, 7, 4, 3, 7],
       [7, 2, 5, 4, 1, 7],
       [5, 1, 4, 0, 9, 5]])

In [26]:
# Find the 0'th index of the latest array you created
a2[0]

array([1. , 2. , 3.3])

In [32]:
# Get the first 2 rows of latest array you created
a2

array([[1. , 2. , 3.3],
       [4. , 5. , 6.5]])

In [31]:
# Get the first 2 values of the first 2 rows of the latest array
a2[:2,:2]

array([1. , 2. , 3.3])

In [33]:
# Create a random array of numbers between 0 & 10 and an array of ones both of size (3, 5), save them both to variables
random_array = np.random.randint(10, size=(3, 5))
random_array

array([[8, 0, 9, 2, 6],
       [3, 8, 2, 4, 2],
       [6, 4, 8, 6, 1]])

In [34]:
# Add the two arrays together
a1+a2

array([[2. , 4. , 6.3],
       [5. , 7. , 9.5]])

In [36]:
# Create another array of ones of shape (5, 3)
b=np.ones([5,3])
b

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [65]:
# Try add the array of ones and the other most recent array together # You can anticipate an error
a1 +a2

array([[2. , 4. , 6.3],
       [5. , 7. , 9.5]])

In [64]:
# Do the same operation you just did but this time with a transpose on one array
a2.T
a2 + a1

array([[2. , 4. , 6.3],
       [5. , 7. , 9.5]])

In [57]:
# Take the latest array to the power of 2 using the python way
np.exp(a2)

array([[  2.71828183,   7.3890561 ,  27.11263892],
       [ 54.59815003, 148.4131591 , 665.14163304]])

In [11]:
# Do the same thing with numpy way


In [70]:
# Find the mean, min, max, standard deviation, variance of the latest array using np.mean()
np.mean(a1)
np.min(a1)
np.max(a1)
np.std(a1)
np.var(a1)


0.6666666666666666

In [82]:
# Create two arrays of random integers between 0 to 10 one of size (3, 3) the other of size (3, 2)
a =np.random.randint(10, size=(3,3))
b =np.random.randint(10, size=(3,2))-
a , b

(array([[2, 9, 2],
        [2, 3, 6],
        [3, 8, 0]]), array([[7, 6],
        [1, 7],
        [0, 8]]))

In [84]:
# Perform a dot product on the two newest arrays you created
np.dot(a,b)

array([[23, 91],
       [17, 81],
       [29, 74]])

In [ ]:
# Create two arrays of random integers between 0 to 10 both of size (4, 3)
c = np.random.randint(10, size=(4, 3))

In [91]:
# Perform a hadamard product on the two newest arrays you created
a1 *a2

array([[ 1. ,  4. ,  9.9],
       [ 4. , 10. , 19.5]])

In [92]:
# Perform a dot product on the two newest arrays you created # Error anticipated
np.dot(a ,b)

array([[23, 91],
       [17, 81],
       [29, 74]])

In [93]:
# Take the latest two arrays, perform a transpose on one of them and then perform a dot product on them both
a.T
b.T
np.dot(a,b)

array([[23, 91],
       [17, 81],
       [29, 74]])

In [95]:
# Create two arrays of random integers between 0 & 10 of the same shape and save them to variables
d = b2 = np.random.randint(10, size=(3,3))
d

array([[0, 1, 0],
       [4, 4, 6],
       [8, 8, 2]])

In [96]:
# Compare the two arrays with '>', '<=' and '==' 
a2>a1
a2<=a1
a2==a1

array([[ True,  True, False],
       [False, False, False]])

In [97]:
# Sort one of the arrays you just created in ascending order
np.argsort(a1)

array([0, 1, 2], dtype=int64)

In [102]:
# Sort the indexes of one of the arrays you just created
np.argmax(a1)

2

In [105]:
# Find the index with the maximum value in one of the arrays you've created
np.argmax(a2, axis=0)

array([1, 1, 1], dtype=int64)

In [108]:
# Create an array with 10 evenly spaced numbers between 1 and 100
random_array = np.random.randint(10, size=(1, 100))
random_array

array([[4, 6, 3, 0, 4, 6, 9, 9, 5, 4, 3, 1, 3, 9, 9, 2, 9, 0, 7, 4, 3, 7,
        6, 1, 0, 3, 7, 1, 2, 0, 0, 2, 4, 2, 0, 0, 7, 9, 1, 2, 1, 2, 6, 0,
        9, 7, 9, 9, 9, 1, 2, 8, 6, 3, 9, 4, 1, 7, 3, 8, 4, 8, 3, 9, 4, 8,
        7, 2, 0, 2, 3, 1, 0, 6, 7, 6, 4, 0, 6, 6, 8, 2, 8, 0, 0, 3, 8, 5,
        2, 0, 3, 8, 2, 8, 6, 3, 2, 9, 4, 4]])

In [110]:
# Find the indexes with the maximum values down the verticial axis of one of the arrays you created
np.argmax(random_array)

6

In [ ]:
# Find the indexes with the minimum values across the horizontal axis of one of the arrays you created
np.argmin(random_array)